---
title: "Devoir 2"
author: "Votre noms d'équipe"
date: "13/03/2024"
output: html_document
---

# À remettre sur Moodle au plus tard le 27 mars 2024 avant le début du cours. 

## Question 1 
### Mise en contexte

Vous êtes impliqué dans un projet dont l'intérêt est d'étudier comment deux espèces bactériennes interagissent entre elles dans un environnement hautement contrôlé (c'est-à-dire une boîte de Petri). Au début de l'expérience, 25 individus de l'espèce *bogustonia proii* et 20 individus de l'espèce *aleastonia predatora* ont été inoculés dans la boîte de Petri. Pendant l'expérience, les individus de chaque espèce ont été comptés indépendamment toutes les heures pendant deux semaines (beaucoup d'efforts et de nuits blanches ont été nécessaires pour ce projet).  

Les données qui ont été recueillies pendant ces deux semaines sont disponibles dans le fichier `2Bacteries.csv`.

Un chercheur impliqué dans le projet pense que la relation entre les deux espèces bactériennes est une relation consommateur-ressource, mais il n'est pas certain de comment construire un modèle pour tester cette hypothèse. Comme il y a plusieurs façons de construire un modèle consommateur-ressource, proposer un modèle consommateur-ressource qui vous permettra de mieux caractériser la dynamique entre les deux espèces. 

*Indice :* Un des chercheurs de l'équipe qui connait très bien l'espèce *bogustonia proii* a remarqué que dans une expérience similaire qui n'a durée que 5 jours, le taux de croissance de cette espèce n'était pas constant. Plus il y avait d'individu moins le taux de croissance était élevé.

### 2 points

a) Présenter le modèle que vous souhaitez utiliser. Assurez-vous de bien définir la notation pour le modèle.

#### Modèle Lotka-Volterra entre l'espèce *bogustonia proii* et l'espèce *aleastonia predatora*  
##### $\frac{dR}{dt} = \alpha R(t) (1 - \frac{R(t)}{K}) - \beta R(t)C(t)$  
##### $\frac{dC}{dt} = \epsilon \beta R(t)C(t) - \delta C(t)$  
$R(t)$ : Taille de la population de *bogustonia proii*  
$C(t)$ : Taille de la population de *aleastonia predatora*  
$\alpha$ : Taux de croissance de *bogustonia proii*  
$K$  : Capacité maximale de support de l'environnement à *bogustonia proii*  
$\beta$ : Coefficient de la force de l'interaction entre les populations  
$\epsilon$ : Taux de transformation de la consommation d'une ressource en nouveau consommateur
$\delta$ : Taux de mortalité de *aleastonia predatora*

***

### 8 points

b) Implémentez le modèle que vous considérez le plus approprié dans R en utilisant les techniques apprises en cours et essayez une série de valeurs différentes pour trouver les meilleures paramètres. Utilisez la corrélation de Pearson pour trouver les paramètres qui correspondent le mieux aux données.

```{r}
#librairie
library(deSolve)

# lecture des données
bact <- read.csv("2Bactéries.csv")

# Créer un nouveau graphique avec la ligne bogustonia proii
plot(x = bact$temps, y = bact$bogustonia_proii, type = "l", col = "green", 
     xlab = "Temps", ylab = "Nb individus", main = "Données bruts des populations de bogustonia proii et aleastonia predatora")

# Ajouter la ligne aleastonia predatora
lines(x = bact$temps, y = bact$aleastonia_predatora, col = "orange")

# Fonction du modele consommateur ressource
C_RVector <- function(t, vars, parms){
  with(as.list(c(parms, vars)), {
    # Modèle consommateur ressoure
    dR <- alpha*R*(1-R/2000) - beta*R*C # dR/dt
    dC <- (epsilon*beta)*R*C - delta*C  # dC/dt
    
    # Résultat
    res <- c(dR=dR, dC=dC)
    return(list(res))
  })
}

# Fonction pour dessiner la solution
dessinSol <- function(ic=c(R=25,C=20), times=bact$temps,func=C_RVector, parms=c(alpha=0.4,beta=0.2,epsilon=1,delta=0.91)) {
  
  # Applique le modele avec les parammetres
  soln <- ode(ic, times, func, parms)
  
  # Trouve les correlations avec du modele
  correlation_R <- cor(bact$bogustonia_proii, soln[,"R"])
  correlation_C <- cor(bact$aleastonia_predatora, soln[,"C"])
  
  # Créer un nouveau graphique avec la ligne du modele bogustonia proii
  plot(x = times, y = soln[,"R"], type = "l", col = "blue", 
       xlab = "Temps", ylab = "Données", 
       main = "Comparaison du modèle avec les données bruts")
  
  # Ajouter la ligne du modele aleastonia predatora
  lines(x = times, y = soln[,"C"], col = "red")
  # Ajouter la ligne brute bogustonia proii
  lines(x = bact$temps, y = bact$bogustonia_proii, col = "green")
  # Ajouter la ligne brute aleastonia predatora
  lines(x = bact$temps, y = bact$aleastonia_predatora, col = "orange")
  
  # presentation de parammetre et correlation
  print(paste("alpha =", parms[1],"beta =", parms[2],"epsilon =", parms[3],"delta =", parms[4]))
  print(paste("Ressource :",round(correlation_R,4)))
  print(paste("Consomateur :",round(correlation_C,4)))
}

# best resultat
dessinSol(parms = c(alpha=0.17,beta=0.0242,epsilon=1.21,delta=0.401),func = C_RVector)

```

***

### 1 point

c) Même si vous n'obtenez pas un modèle qui s'adapte très bien aux données, expliquez brièvement comment vous pensez que les différents modèles que vous obtenez peuvent aider à rejeter (ou non) l'hypothèse proposée par ce chercheur.

L'hypothèse que la relation entre les deux espèces bactériennes est une relation consommateur-ressource peut être soutenue puisque le modèle correspond à 96,4% pour la population ressource(*bogustonia proii*) et à 95,5% pour la population consommatrice(*aleastonia predatora*).  
Sinon, le modèle utilisé prend en compte seulement la mortalité de la proie due à la prédation. De même pour les prédateurs, dont l'ajout de nouveaux individus est uniquement lié à la consommation de proie. Ainsi, toute diminution de la population des proies ou toute augmentation de la population des prédateurs dont les données brutes et le modèle se superposent confirme la relation consommateur-ressource entre des deux espèces. 

***

### 1 point

d) Après avoir étudié les données en utilisant le modèle ressource-consommateur à la question précédent, proposez une nouvelle expérience qui aiderait à donner des réponses plus précises sur les facteurs générant le comportement périodique trouvé pour les deux espèces bactériennes.

Assurez-vous que l'expérience puisse être réalisée dans un délai raisonnable (au maximum 2 semaines).

Il serait intéressant de refaire la même expérience, mais de varier le nombre de départ de ressource avec un grand nombre ou le nombre de consommateurs pour voir si le comportement périodique est affecté. Cela permettrait de confirmer le portrait de phase lié au modèle.  